export interface ServiceData {
  slug: string;
  name: string;
  tagline: string;
  heroHeading: string;
  heroSub: string;
  description: string;
  includes: string[];
  turnaround: string;
  startingPrice: string;
  priceNote: string;
  color: string;
  keywords: string[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
}

export const SERVICES: ServiceData[] = [
  {
    slug: "essay-writing",
    name: "Essay Writing",
    tagline: "Any essay. Any subject. Any deadline.",
    heroHeading: "Professional Essay Writing Service — Delivered in Hours",
    heroSub: "Get a fully written, plagiarism-free essay from a vetted academic writer. Deadlines from 1 hour to 24 hours. Starting at $15/page.",
    description: "Whether it's an argumentative essay, an analytical piece, a reflective journal, or a compare-and-contrast assignment — WriteProf has expert writers ready to deliver. Every essay is written from scratch, properly cited, and tailored to your exact instructions.",
    includes: ["Argumentative essays", "Analytical essays", "Reflective essays", "Compare & contrast", "Narrative essays", "Descriptive essays", "Persuasive essays", "Expository essays"],
    turnaround: "From 1 hour",
    startingPrice: "$15",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-brand-600 to-brand-400",
    keywords: ["pay someone to write my essay", "essay writing service", "buy essay online", "essay writer for hire", "urgent essay help", "same day essay writer", "write my essay for me", "professional essay writing service", "cheap essay writing service", "online essay writer"],
    faqs: [
      { q: "Can you write my essay in 1 hour?", a: "Yes. Our emergency writers can complete essays as fast as 1 hour for shorter assignments. Longer essays (3,000+ words) require at least 3–6 hours for quality work." },
      { q: "Will my essay be plagiarism-free?", a: "Every essay passes Turnitin and Copyscape before delivery. You receive a plagiarism report with your order. We guarantee 0% plagiarism or a full refund." },
      { q: "What citation styles do you use?", a: "Our writers support APA, MLA, Chicago, Harvard, Vancouver, and IEEE. Just specify your required format when placing the order." },
      { q: "Can I request revisions?", a: "Yes — unlimited free revisions until you're satisfied. Payment is held in escrow and released only when you approve." },
      { q: "How much does an essay cost?", a: "Essays start at $15/page (275 words) for 24-hour delivery. Emergency 1-hour essays cost $75/page. The price scales with urgency and word count." },
    ],
    relatedSlugs: ["research-papers", "proofreading-editing", "dissertations"],
  },
  {
    slug: "research-papers",
    name: "Research Papers",
    tagline: "Fully cited. Expert-written. On time.",
    heroHeading: "Research Paper Writing Service — Expert Writers, Rush Delivery",
    heroSub: "Buy a research paper written by a subject-matter expert. Properly cited, peer-reviewed quality, delivered in 3–24 hours. From $26/page.",
    description: "Our research paper writers hold Masters and PhD degrees in their fields. Every paper is backed by credible sources, follows your required citation style, and meets the academic standards of your institution.",
    includes: ["Term papers", "Literature reviews", "Empirical research papers", "Scientific reports", "Annotated bibliographies", "Research proposals", "Position papers", "Review articles"],
    turnaround: "From 3 hours",
    startingPrice: "$26",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-cyan-600 to-cyan-400",
    keywords: ["buy research paper online", "research paper writing service", "pay for research paper", "write my research paper", "research paper writer for hire", "urgent research paper help", "custom research paper", "academic research writing service", "research paper in 24 hours", "cheap research paper writing"],
    faqs: [
      { q: "How quickly can you write a research paper?", a: "Research papers can be completed in as little as 3 hours for shorter papers (under 5 pages). Longer papers (10–20 pages) typically need 6–12 hours for thorough research and writing." },
      { q: "Do writers use real academic sources?", a: "Yes. Writers use peer-reviewed journals, academic databases (JSTOR, PubMed, Google Scholar), and credible publications. You can request specific sources too." },
      { q: "Can you write a research paper in any subject?", a: "Yes — psychology, nursing, business, history, biology, chemistry, law, economics, sociology, computer science, and more. We match you with a writer who specialises in your subject." },
      { q: "Will the paper pass Turnitin?", a: "Every research paper is written from scratch and passes Turnitin before delivery. We include a plagiarism report with every order." },
      { q: "What if I need a very long paper?", a: "We handle papers of any length. For papers over 20 pages, we recommend a 12–24 hour deadline to ensure quality research and thorough writing." },
    ],
    relatedSlugs: ["essay-writing", "dissertations", "case-studies"],
  },
  {
    slug: "dissertations",
    name: "Dissertations & Theses",
    tagline: "PhD and Masters-level writing support.",
    heroHeading: "Dissertation Writing Service — Chapter by Chapter or Full",
    heroSub: "Get expert help with your dissertation or thesis. Full writing, individual chapters, proposals, or literature reviews — delivered by PhD writers.",
    description: "WriteProf connects you with PhD and Masters-qualified writers who understand dissertation methodology, academic rigour, and the exact standards your institution expects. Whether you need a full dissertation or just one chapter, we deliver on time.",
    includes: ["Full dissertations", "Individual chapters", "Research proposals & abstracts", "Literature reviews", "Methodology chapters", "Data analysis & results", "Discussion & conclusion chapters", "Thesis writing"],
    turnaround: "From 6 hours",
    startingPrice: "$37",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-violet-600 to-violet-400",
    keywords: ["dissertation writing service", "write my dissertation", "pay for dissertation help", "dissertation writer for hire", "thesis writing service", "buy dissertation online", "dissertation chapter help", "urgent dissertation writing", "PhD dissertation writing service", "masters dissertation help"],
    faqs: [
      { q: "Can you write an entire dissertation?", a: "Yes. Our PhD-level writers handle full dissertations from the introduction to the conclusion and reference list. We work chapter by chapter or as a complete project." },
      { q: "How long does a dissertation take?", a: "For individual chapters (5,000–8,000 words), we typically deliver in 12–24 hours. Full dissertations (15,000–80,000 words) require custom timelines — contact us to discuss." },
      { q: "Will the dissertation follow my university's guidelines?", a: "Yes. Share your university's formatting guide, referencing style, and structure requirements when placing the order. Writers follow them exactly." },
      { q: "Can I get help with just one chapter?", a: "Absolutely. You can order any single chapter — literature review, methodology, results, discussion, or conclusion — as a standalone order." },
      { q: "Is dissertation help confidential?", a: "100%. We operate under a strict NDA policy. Your identity, your institution, and your order details are never shared with anyone." },
    ],
    relatedSlugs: ["research-papers", "essay-writing", "proofreading-editing"],
  },
  {
    slug: "proofreading-editing",
    name: "Proofreading & Editing",
    tagline: "Your ideas, perfected.",
    heroHeading: "Professional Proofreading & Editing Service — Fast Turnaround",
    heroSub: "Grammar, clarity, flow, structure, citations — all polished by an expert editor. From $8/page. Turnaround from 1 hour.",
    description: "Our editors refine your writing without changing your voice. Whether it's an essay, research paper, dissertation, or business document — we fix grammar, improve clarity, correct citations, and ensure your work reads professionally.",
    includes: ["Grammar & spelling corrections", "Clarity & readability improvements", "Sentence structure & flow", "Citation formatting (APA, MLA, Chicago, etc.)", "Plagiarism check", "Consistency review", "Academic tone adjustment", "Word count trimming"],
    turnaround: "From 1 hour",
    startingPrice: "$8",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-teal-600 to-teal-400",
    keywords: ["proofreading service online", "essay proofreading service", "academic editing service", "dissertation proofreading", "professional proofreading", "cheap proofreading service", "edit my essay", "grammar check service", "thesis editing service", "rush proofreading service"],
    faqs: [
      { q: "What's the difference between proofreading and editing?", a: "Proofreading fixes grammar, spelling, and punctuation. Editing goes deeper — improving clarity, flow, structure, and academic tone. WriteProf's service includes both." },
      { q: "How fast can you proofread my document?", a: "Short documents (under 10 pages) can be returned in 1 hour. Longer documents (dissertations, theses) typically take 3–6 hours." },
      { q: "Will the editor change my writing style?", a: "No. Our editors preserve your voice and only improve clarity and correctness. The work remains entirely yours." },
      { q: "Can you fix my citations too?", a: "Yes. Specify your required citation style (APA, MLA, Chicago, Harvard, etc.) and our editors will correct and format all references." },
      { q: "Do you proofread dissertations?", a: "Yes — full dissertations, individual chapters, or proposals. We also offer Turnitin checks as part of the proofreading process." },
    ],
    relatedSlugs: ["essay-writing", "dissertations", "research-papers"],
  },
  {
    slug: "copywriting",
    name: "Copywriting",
    tagline: "Words that convert. Delivered in hours.",
    heroHeading: "Professional Copywriting Service — Conversion-Focused, Fast",
    heroSub: "Hire a specialist copywriter for landing pages, ads, email sequences, and sales copy. Delivered in 1–24 hours. From $20/page.",
    description: "WriteProf's copywriters understand psychology, persuasion, and your audience. From Google Ads to full sales pages, we write copy that drives action — delivered fast when you need it most.",
    includes: ["Landing page copy", "Google & Meta ad copy", "Email campaigns & sequences", "Product descriptions", "Sales pages", "VSL scripts", "Website copy", "Social media captions"],
    turnaround: "From 1 hour",
    startingPrice: "$20",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-pink-600 to-pink-400",
    keywords: ["copywriting service", "hire a copywriter", "landing page copywriter", "sales page writer", "email copywriter", "ad copy writer", "professional copywriter for hire", "conversion copywriting service", "freelance copywriter", "rush copywriting service"],
    faqs: [
      { q: "What types of copy do you write?", a: "Landing pages, email sequences, Google Ads, Meta/Facebook Ads, product descriptions, sales pages, website copy, VSL scripts, and social media content." },
      { q: "How quickly can you deliver copy?", a: "Short pieces (ads, email, product descriptions) can be delivered in 1–3 hours. Full sales pages and landing pages typically need 3–6 hours." },
      { q: "Do you write for specific industries?", a: "Yes — eCommerce, SaaS, health & wellness, finance, education, real estate, and more. We match you with a copywriter who has experience in your niche." },
      { q: "Can I provide brand guidelines?", a: "Absolutely. Share your tone of voice, brand guide, target audience, and any examples — writers follow them precisely." },
      { q: "Do you offer revision rounds?", a: "Yes — unlimited revisions until you're satisfied with the copy. Payment is held in escrow and released only on your approval." },
    ],
    relatedSlugs: ["blog-seo-content", "email-writing", "business-writing"],
  },
  {
    slug: "blog-seo-content",
    name: "Blog & SEO Content",
    tagline: "Content that ranks. Written fast.",
    heroHeading: "Blog & SEO Content Writing Service — Rank Higher, Faster",
    heroSub: "Keyword-targeted blog posts, pillar pages, and SEO articles written by professional content writers. Optimised to rank. From $15/page.",
    description: "Our SEO content writers know how to structure content for search engines without sacrificing readability. Every article is keyword-researched, properly formatted (H1/H2/H3), and written to engage readers and satisfy search intent.",
    includes: ["Blog posts", "SEO articles", "Pillar pages & topic clusters", "How-to guides", "Listicles", "Product comparison posts", "FAQ pages", "Content refreshes & updates"],
    turnaround: "From 3 hours",
    startingPrice: "$15",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-green-600 to-green-400",
    keywords: ["blog writing service", "SEO content writing service", "hire blog writer", "SEO article writing service", "content writing service", "blog post writing service", "SEO copywriting service", "buy blog content", "professional blog writer", "content writing for websites"],
    faqs: [
      { q: "Will the content be SEO optimised?", a: "Yes. Writers structure content with proper H1/H2/H3 headings, keyword placement, meta descriptions, and internal linking suggestions — all SEO best practices." },
      { q: "Can I provide my target keywords?", a: "Absolutely. Share your target keywords, search intent, and competitor URLs and writers will optimise the content around them." },
      { q: "How long should a blog post be for SEO?", a: "For most competitive keywords, 1,500–2,500 words performs best. Pillar pages targeting broad topics typically need 3,000–5,000 words." },
      { q: "Do you write for specific industries?", a: "Yes — finance, health, tech, education, legal, eCommerce, real estate, and more. We match you with a writer who understands your niche." },
      { q: "Can you refresh old blog posts?", a: "Yes. Share your existing post and our writers will update the content, add new information, improve keyword density, and restructure for better rankings." },
    ],
    relatedSlugs: ["copywriting", "email-writing", "business-writing"],
  },
  {
    slug: "business-writing",
    name: "Business Writing",
    tagline: "Professional documents that mean business.",
    heroHeading: "Business Writing Service — Proposals, Reports & Plans, Fast",
    heroSub: "Get professional business documents written by experienced business writers. Proposals, plans, executive summaries, and reports. From $26/page.",
    description: "Our business writers have real-world corporate and consulting experience. They produce documents that communicate with authority, meet professional standards, and make the right impression on clients, investors, and stakeholders.",
    includes: ["Business proposals", "Business plans", "Executive summaries", "Annual reports", "White papers", "Internal memos", "Board presentations", "RFP responses"],
    turnaround: "From 2 hours",
    startingPrice: "$26",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-amber-600 to-amber-400",
    keywords: ["business writing service", "business proposal writer", "business plan writing service", "professional business writer", "executive summary writer", "white paper writing service", "business report writing", "hire business writer", "corporate writing service", "urgent business writing"],
    faqs: [
      { q: "Can you write a full business plan?", a: "Yes — full business plans including executive summary, market analysis, financial projections, and operational plan. Typical turnaround is 12–24 hours." },
      { q: "Do you write business proposals?", a: "Yes. Our writers craft proposals tailored to your client's needs, with a clear value proposition, scope of work, and pricing structure." },
      { q: "Can you write white papers?", a: "Absolutely. White papers require deep research and authoritative writing — our business writers produce publication-ready documents." },
      { q: "How long do business documents take?", a: "Short documents (memos, executive summaries) can be ready in 2–4 hours. Business plans and white papers typically take 12–24 hours." },
      { q: "Do you sign NDAs?", a: "Yes. All writers operate under our platform NDA. Your business information, strategies, and client details remain strictly confidential." },
    ],
    relatedSlugs: ["copywriting", "case-studies", "presentations"],
  },
  {
    slug: "case-studies",
    name: "Case Studies",
    tagline: "Academic and business case studies, done right.",
    heroHeading: "Case Study Writing Service — Academic & Business, Rush Delivery",
    heroSub: "Structured, well-analysed case studies written by experts familiar with SWOT, Porter's 5 Forces, and academic frameworks. From $26/page.",
    description: "Our case study writers combine academic rigour with real business analysis. Whether it's a university assignment or a marketing case study for your business, we deliver structured, insightful work on time.",
    includes: ["Academic case studies", "Business case studies", "SWOT analysis", "PESTLE analysis", "Porter's 5 Forces", "Market analysis", "Industry reports", "Strategic recommendations"],
    turnaround: "From 3 hours",
    startingPrice: "$26",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-orange-600 to-orange-400",
    keywords: ["case study writing service", "write my case study", "buy case study online", "academic case study help", "business case study writer", "SWOT analysis writing service", "case study assignment help", "urgent case study writing", "case study writer for hire", "professional case study writing"],
    faqs: [
      { q: "What frameworks do your case study writers use?", a: "SWOT, PESTLE, Porter's 5 Forces, McKinsey 7S, BCG Matrix, Ansoff Matrix, and more — depending on what your case study requires." },
      { q: "Can you write a business case study?", a: "Yes — both academic case studies for university and professional case studies for marketing, investor decks, or internal business use." },
      { q: "How long does a case study take?", a: "A 2,000–4,000 word case study typically takes 3–6 hours. Longer, research-heavy case studies need 6–12 hours." },
      { q: "Do you include real examples and data?", a: "Yes. Writers research real-world examples, cite industry reports, and use credible data sources to back up the analysis." },
      { q: "Can I provide the case scenario?", a: "Absolutely. Share your case scenario, relevant company information, and required analysis frameworks — writers work from your brief." },
    ],
    relatedSlugs: ["research-papers", "business-writing", "essay-writing"],
  },
  {
    slug: "lab-reports",
    name: "Lab Reports & STEM",
    tagline: "STEM writing by specialists who understand the science.",
    heroHeading: "Lab Report Writing Service — STEM Specialists, Fast Delivery",
    heroSub: "Get your lab report, technical report, or STEM assignment written by a qualified science or engineering specialist. From $37/page.",
    description: "Writing about science requires more than good writing — it requires understanding the subject. Our STEM writers hold degrees in biology, chemistry, physics, engineering, and mathematics. They produce technically accurate, well-structured reports that meet lab report conventions.",
    includes: ["Biology lab reports", "Chemistry lab reports", "Physics lab reports", "Engineering technical reports", "Data analysis write-ups", "Mathematical proofs", "Scientific literature reviews", "STEM assignments"],
    turnaround: "From 3 hours",
    startingPrice: "$37",
    priceNote: "per page (275 words) for 24-hour delivery",
    color: "from-sky-600 to-sky-400",
    keywords: ["lab report writing service", "write my lab report", "buy lab report online", "chemistry lab report help", "biology lab report writing", "STEM writing service", "technical report writing service", "lab report writer for hire", "physics lab report help", "engineering report writing service"],
    faqs: [
      { q: "Can you write a biology or chemistry lab report?", a: "Yes. We have writers with degrees in biology, chemistry, physics, and related sciences who understand lab report structure: hypothesis, methods, results, discussion, conclusion." },
      { q: "How quickly can you write a lab report?", a: "Most lab reports (3–8 pages) can be delivered in 3–6 hours. Longer, data-heavy reports may need 6–12 hours." },
      { q: "Can I share my raw data and results?", a: "Yes — share your data, lab notes, and any graphs or tables. Writers will interpret and write up the results and discussion sections around them." },
      { q: "Do STEM writers cite sources properly?", a: "Yes. Scientific citations follow IEEE, Vancouver, APA, or whatever format your department requires." },
      { q: "Can you help with engineering reports?", a: "Absolutely — technical reports, feasibility studies, engineering proposals, and design reports for civil, mechanical, electrical, and software engineering." },
    ],
    relatedSlugs: ["research-papers", "essay-writing", "proofreading-editing"],
  },
  {
    slug: "presentations",
    name: "Presentations & Slides",
    tagline: "Slide decks that communicate and persuade.",
    heroHeading: "Presentation Writing Service — Slides & Speaker Notes, Fast",
    heroSub: "Get a compelling presentation written by an expert — complete with speaker notes. Academic defences, pitch decks, and business presentations. From $15/slide.",
    description: "A great presentation starts with great content. Our writers craft the narrative, structure the flow, and write the slide copy and speaker notes. Whether it's a dissertation defence, investor pitch, or board presentation — we deliver a script that works.",
    includes: ["PowerPoint slide copy", "Speaker notes", "Academic dissertation defences", "Business pitch decks", "Board presentations", "Conference presentations", "Sales presentations", "Webinar scripts"],
    turnaround: "From 2 hours",
    startingPrice: "$15",
    priceNote: "per slide for 24-hour delivery",
    color: "from-rose-600 to-rose-400",
    keywords: ["presentation writing service", "PowerPoint writing service", "pitch deck writer", "speaker notes writing", "academic presentation help", "presentation script writer", "slide deck writing service", "hire presentation writer", "business presentation writing", "dissertation defence presentation"],
    faqs: [
      { q: "Do you write the slide content or design the slides?", a: "We write the slide text and speaker notes. If you need design work, we can recommend that separately — our focus is on the written content and narrative." },
      { q: "Can you write speaker notes for my existing slides?", a: "Yes — share your existing slides and we'll write detailed speaker notes to go with each one." },
      { q: "How do you price presentations?", a: "Presentations are priced per slide — from $15/slide for standard delivery. Price increases for shorter turnarounds or complex technical content." },
      { q: "Can you write a pitch deck for investors?", a: "Yes. Our business writers structure investor pitch decks with a compelling narrative: problem, solution, market size, traction, team, and ask." },
      { q: "How quickly can a presentation be written?", a: "A 10–15 slide presentation can typically be written in 2–4 hours. Longer decks (20–30 slides) need 4–8 hours." },
    ],
    relatedSlugs: ["business-writing", "copywriting", "case-studies"],
  },
  {
    slug: "email-writing",
    name: "Email & Communication",
    tagline: "Emails that get opened, read, and replied to.",
    heroHeading: "Email Writing Service — Campaigns, Sequences & Business Emails",
    heroSub: "Professional emails, cold outreach sequences, and newsletters written by specialist email copywriters. Delivered in 1–24 hours. From $20/piece.",
    description: "Email is the highest-ROI channel in marketing — but only when the copy is right. Our email writers understand subject lines, open rates, click-through rates, and conversion. From cold outreach to drip sequences, we write emails people actually respond to.",
    includes: ["Cold email sequences", "Email drip campaigns", "Newsletter copy", "Business correspondence", "Follow-up sequences", "Outreach templates", "Transactional email copy", "Re-engagement campaigns"],
    turnaround: "From 1 hour",
    startingPrice: "$20",
    priceNote: "per email for 24-hour delivery",
    color: "from-indigo-600 to-indigo-400",
    keywords: ["email writing service", "email copywriter", "cold email writing service", "email marketing writer", "hire email copywriter", "email sequence writer", "newsletter writing service", "business email writing", "email campaign writing service", "professional email writer"],
    faqs: [
      { q: "Can you write a full email sequence?", a: "Yes — welcome sequences, onboarding drips, sales sequences, re-engagement campaigns, and cold outreach sequences of any length." },
      { q: "How quickly can emails be written?", a: "Single emails or short sequences (3–5 emails) can be delivered in 1–3 hours. Longer campaigns (10+ emails) need 6–12 hours." },
      { q: "Do you write cold outreach emails?", a: "Yes. Our cold email writers focus on deliverability, personalisation, and getting replies — not just opens." },
      { q: "Can I provide my product/service details?", a: "Yes — the more context you give (audience, offer, tone, past campaigns), the better the emails will perform." },
      { q: "Do you write B2B or B2C emails?", a: "Both. We have writers experienced in B2B SaaS, eCommerce, professional services, coaching, and more." },
    ],
    relatedSlugs: ["copywriting", "blog-seo-content", "business-writing"],
  },
  {
    slug: "cv-resume",
    name: "CVs, Resumes & Cover Letters",
    tagline: "ATS-optimised. Hiring-manager approved.",
    heroHeading: "CV & Resume Writing Service — Stand Out, Get Interviews",
    heroSub: "ATS-optimised CVs, resumes, and cover letters written by career coaches who know what hiring managers want. From $49/document.",
    description: "Your CV gets 7 seconds of attention before a recruiter moves on. Our career writers know exactly what hiring managers and ATS systems look for — keyword-rich, achievement-focused, and formatted to pass automated screening before a human even sees it.",
    includes: ["CVs & resumes", "Cover letters", "LinkedIn profile rewrites", "Personal statements", "Graduate school application essays", "Executive bios", "ATS optimisation", "Career change CVs"],
    turnaround: "From 2 hours",
    startingPrice: "$49",
    priceNote: "per document for 24-hour delivery",
    color: "from-lime-600 to-lime-400",
    keywords: ["CV writing service", "resume writing service", "cover letter writing service", "professional CV writer", "ATS optimised CV", "hire CV writer", "resume writer for hire", "LinkedIn profile writer", "personal statement writing service", "career coach CV writing"],
    faqs: [
      { q: "Will my CV pass ATS screening?", a: "Yes. Our writers optimise CVs for Applicant Tracking Systems — using the right keywords, formatting, and structure to pass automated screening." },
      { q: "Can you write a cover letter too?", a: "Yes — cover letters are available as add-ons or standalone orders. We tailor each letter to the specific job description you provide." },
      { q: "Do you write CVs for career changers?", a: "Absolutely. Career change CVs require a different approach — highlighting transferable skills and reframing experience for a new industry." },
      { q: "Can you rewrite my LinkedIn profile?", a: "Yes. We rewrite LinkedIn summaries, headlines, and experience sections to attract recruiters and align with your target roles." },
      { q: "How quickly can you write my CV?", a: "Most CVs and resumes are delivered within 2–6 hours. We may need up to 24 hours for executive-level CVs with extensive experience." },
    ],
    relatedSlugs: ["copywriting", "proofreading-editing", "business-writing"],
  },
];

export function getService(slug: string): ServiceData | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return SERVICES.map((s) => s.slug);
}
