export interface SubjectData {
  slug: string;
  name: string;
  heroHeading: string;
  heroSub: string;
  description: string;
  paperTypes: string[];
  topics: string[];
  color: string;
  keywords: string[];
  faqs: { q: string; a: string }[];
  relatedSubjects: string[];
}

export const SUBJECTS: SubjectData[] = [
  {
    slug: "nursing",
    name: "Nursing",
    heroHeading: "Nursing Essay & Assignment Writing Service — Expert Help, Fast",
    heroSub: "Get nursing essays, care plans, case studies, and reflective journals written by qualified nursing professionals. Delivered in 1–24 hours. From $15/page.",
    description: "Our nursing writers hold BSN, MSN, and PhD in Nursing. They understand clinical terminology, nursing theories (Orem, Roy, Watson), evidence-based practice, and NMC/ANA standards. Whether it's a reflective essay, SOAP note, or dissertation chapter — we deliver work that meets the standard of your programme.",
    paperTypes: ["Nursing essays", "Care plans", "SOAP notes", "Case studies", "Reflective journals", "Nursing dissertations", "Literature reviews", "Nursing research papers"],
    topics: ["Evidence-based practice", "Patient care & safety", "Mental health nursing", "Paediatric nursing", "Pharmacology", "Nursing ethics", "Leadership in nursing", "Community health nursing"],
    color: "from-blue-600 to-cyan-400",
    keywords: ["nursing essay writing service", "write my nursing essay", "nursing assignment help", "pay someone to write nursing essay", "nursing care plan writer", "nursing essay help online", "nursing paper writing service", "cheap nursing essay writing", "urgent nursing essay help", "nursing dissertation writing service"],
    faqs: [
      { q: "Can you write a nursing reflective essay?", a: "Yes. Our nursing writers are familiar with Gibbs, Driscoll, and Johns reflective models. Just tell us which model your programme requires." },
      { q: "Do your writers understand NMC/ANA standards?", a: "Yes. Our nursing writers are trained to UK NMC and US ANA standards, as well as APA 7th edition referencing commonly used in nursing programmes." },
      { q: "Can you write a nursing care plan?", a: "Absolutely. We write individualised care plans including nursing diagnoses, goals, interventions, and evaluation — in the format your programme requires." },
      { q: "How fast can you write a nursing essay?", a: "Short nursing essays (1,000–2,000 words) can be delivered in 1–3 hours. Longer nursing assignments and dissertations need 6–24 hours." },
      { q: "Is nursing essay help confidential?", a: "100%. Your identity, institution, and order details are protected under our NDA policy and never shared with anyone." },
    ],
    relatedSubjects: ["psychology", "biology", "education"],
  },
  {
    slug: "psychology",
    name: "Psychology",
    heroHeading: "Psychology Essay & Research Paper Writing Service — Expert Help",
    heroSub: "Get psychology essays, research papers, case studies, and literature reviews written by psychology graduates. Delivered in 1–24 hours. From $15/page.",
    description: "Our psychology writers hold degrees in clinical, educational, forensic, and social psychology. They understand psychological theories, research methods (qualitative and quantitative), APA formatting, and the ethical frameworks your assignments require.",
    paperTypes: ["Psychology essays", "Research papers", "Case studies", "Literature reviews", "Lab reports", "Reflective journals", "Psychology dissertations", "Critical analysis papers"],
    topics: ["Cognitive psychology", "Developmental psychology", "Abnormal psychology", "Social psychology", "Forensic psychology", "Neuropsychology", "Psychotherapy theories", "Research methods & statistics"],
    color: "from-purple-600 to-violet-400",
    keywords: ["psychology essay writing service", "write my psychology essay", "psychology paper help", "pay someone to write psychology essay", "psychology assignment help", "psychology research paper writing service", "psychology case study writer", "urgent psychology essay help", "psychology dissertation help", "buy psychology essay online"],
    faqs: [
      { q: "Can you write a psychology case study?", a: "Yes. Our psychology writers produce clinical case studies with diagnosis, background, psychological assessment, treatment plan, and theoretical analysis." },
      { q: "Do writers use APA referencing?", a: "Yes — APA 7th edition is standard for psychology. Writers cite peer-reviewed journals (PsycINFO, PubMed, Google Scholar) and format references correctly." },
      { q: "Can you write about specific psychological theories?", a: "Yes — Freudian psychoanalysis, CBT, Piaget's cognitive development, Maslow, Erikson, Bandura, and any other theory your assignment covers." },
      { q: "Can you help with research methods sections?", a: "Absolutely. Our writers handle quantitative (statistical analysis) and qualitative (thematic analysis, grounded theory) methodology sections." },
      { q: "How quickly can you write a psychology essay?", a: "Essays under 2,000 words can be delivered in 1–3 hours. Longer research papers and dissertations need 6–24 hours." },
    ],
    relatedSubjects: ["nursing", "sociology", "education"],
  },
  {
    slug: "business",
    name: "Business & Management",
    heroHeading: "Business Essay & Assignment Writing Service — Fast, Professional",
    heroSub: "Get business essays, reports, case studies, and management assignments written by MBA-qualified writers. Delivered in 1–24 hours. From $15/page.",
    description: "Our business writers hold MBA, MSc in Management, and related qualifications. They understand business frameworks (SWOT, Porter's, BCG), academic referencing, and the real-world context your assignments require — whether it's strategic management, HRM, finance, or entrepreneurship.",
    paperTypes: ["Business essays", "Management reports", "Case studies", "Business plans", "Marketing plans", "HRM assignments", "Finance reports", "Strategic management papers"],
    topics: ["Strategic management", "Human resource management", "Marketing management", "Entrepreneurship", "Corporate finance", "Organisational behaviour", "Supply chain management", "International business"],
    color: "from-amber-600 to-yellow-400",
    keywords: ["business essay writing service", "management assignment help", "write my business essay", "MBA essay writing service", "business case study help", "pay someone to write business essay", "business management assignment help", "urgent business essay writing", "business report writing service", "buy business essay online"],
    faqs: [
      { q: "Can you write a business management essay?", a: "Yes — strategic management, HRM, marketing, operations, organisational behaviour, entrepreneurship, and more. Writers apply the correct frameworks and models." },
      { q: "Do writers use real business examples?", a: "Yes. Writers reference real companies (Apple, Amazon, Tesla, etc.) with credible sources (Harvard Business Review, Bloomberg, Financial Times) to support arguments." },
      { q: "Can you write a full business plan?", a: "Yes — full business plans with executive summary, market analysis, financial projections, and operational plan. Typical turnaround is 12–24 hours." },
      { q: "What referencing styles do you use for business?", a: "Harvard is most common for business, but we also do APA, MLA, Chicago, and OSCOLA. Specify your requirement when ordering." },
      { q: "Can you write a marketing plan?", a: "Yes — full marketing plans with situational analysis, target market, marketing mix (4Ps/7Ps), budget, and implementation timeline." },
    ],
    relatedSubjects: ["economics", "law", "sociology"],
  },
  {
    slug: "law",
    name: "Law",
    heroHeading: "Law Essay & Assignment Writing Service — Legal Experts, Fast",
    heroSub: "Get law essays, problem questions, case analyses, and dissertations written by qualified legal professionals. Delivered in 1–24 hours. From $15/page.",
    description: "Our law writers hold LLB, LLM, and Barrister/Solicitor qualifications. They understand IRAC/ILAC methodology, legal citation (OSCOLA, Bluebook), case law analysis, and statutory interpretation. From contract law to human rights — we cover every area of law.",
    paperTypes: ["Law essays", "Problem questions (IRAC/ILAC)", "Case analyses", "Legal memos", "Mooting submissions", "Law dissertations", "Contract law papers", "Criminal law assignments"],
    topics: ["Contract law", "Criminal law", "Tort law", "Constitutional law", "Human rights law", "Company law", "International law", "Land law & equity"],
    color: "from-slate-600 to-slate-400",
    keywords: ["law essay writing service", "legal essay help", "write my law essay", "pay someone to write law essay", "law assignment help", "law dissertation writing service", "IRAC essay help", "OSCOLA referencing help", "contract law essay help", "urgent law essay writing"],
    faqs: [
      { q: "Can you answer law problem questions using IRAC?", a: "Yes. Our law writers are trained in IRAC (Issue, Rule, Application, Conclusion) and ILAC methodology — the standard format for problem questions in UK and Australian law programmes." },
      { q: "Do writers use OSCOLA referencing?", a: "Yes. OSCOLA is standard for UK law. We also support Bluebook (US), APA, and other citation styles depending on your institution." },
      { q: "Can you analyse case law?", a: "Absolutely. Our writers can analyse landmark cases, apply ratio decidendi and obiter dicta, and discuss precedent in the context of your question." },
      { q: "Can you write a law dissertation?", a: "Yes — full law dissertations from research proposal to conclusion. Our LLM-qualified writers handle doctrinal, socio-legal, and comparative research approaches." },
      { q: "How quickly can a law essay be written?", a: "Law essays of 1,500–3,000 words can typically be delivered in 3–6 hours. Longer problem questions and dissertations need 12–24 hours." },
    ],
    relatedSubjects: ["business", "political-science", "sociology"],
  },
  {
    slug: "history",
    name: "History",
    heroHeading: "History Essay Writing Service — Expert Historians, Fast Delivery",
    heroSub: "Get history essays, research papers, and dissertations written by history graduates with deep subject knowledge. Delivered in 1–24 hours. From $15/page.",
    description: "Our history writers hold degrees in modern history, ancient history, art history, and related disciplines. They understand historiography, primary and secondary source analysis, and the argumentative essay structure expected at degree level.",
    paperTypes: ["History essays", "Research papers", "Source analysis", "Historiographical essays", "Comparative history papers", "History dissertations", "Book reviews", "Document analysis"],
    topics: ["World War I & II", "Cold War history", "American history", "British history", "Ancient civilisations", "Colonial history", "Civil rights movement", "Modern European history"],
    color: "from-brown-600 to-amber-600",
    keywords: ["history essay writing service", "write my history essay", "history paper help", "pay someone to write history essay", "history assignment help", "history dissertation writing", "urgent history essay help", "buy history essay online", "history research paper writing service", "history essay writer for hire"],
    faqs: [
      { q: "Can you write an essay on any historical period?", a: "Yes — ancient history, medieval, early modern, 19th century, World Wars, Cold War, post-colonial, and contemporary history. We match you with a writer specialising in your period." },
      { q: "Can writers analyse primary sources?", a: "Yes. Our history writers are trained in source criticism — analysing primary documents for provenance, purpose, audience, and historical significance." },
      { q: "What citation style is used for history?", a: "Chicago/Turabian is most common for history. We also support Harvard, MLA, and MHRA. Specify your requirement when ordering." },
      { q: "Can you write a historiographical essay?", a: "Yes — essays that critically compare how different historians have interpreted the same historical event or period, with proper engagement with the literature." },
      { q: "How fast can a history essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Longer research papers and dissertations need 6–24 hours." },
    ],
    relatedSubjects: ["political-science", "sociology", "english-literature"],
  },
  {
    slug: "sociology",
    name: "Sociology",
    heroHeading: "Sociology Essay Writing Service — Expert Sociologists, Fast",
    heroSub: "Get sociology essays, research papers, and dissertations written by sociology graduates. Delivered in 1–24 hours. From $15/page.",
    description: "Our sociology writers understand sociological theory (Marx, Weber, Durkheim, Giddens), qualitative and quantitative research methods, and the critical analysis expected at university level. From social inequality to globalisation — we cover every strand of sociological inquiry.",
    paperTypes: ["Sociology essays", "Research papers", "Literature reviews", "Theoretical analysis papers", "Sociology dissertations", "Case studies", "Research proposals", "Policy analysis papers"],
    topics: ["Social inequality & stratification", "Race & ethnicity", "Gender & feminism", "Crime & deviance", "Religion & society", "Globalisation", "Education & society", "Family & relationships"],
    color: "from-rose-600 to-pink-400",
    keywords: ["sociology essay writing service", "write my sociology essay", "sociology paper help", "pay someone to write sociology essay", "sociology assignment help", "sociology dissertation writing", "urgent sociology essay help", "buy sociology essay online", "sociology research paper writing service", "sociology essay writer for hire"],
    faqs: [
      { q: "Can you apply sociological theories to my essay?", a: "Yes — Marxist, Functionalist, Feminist, Interactionist, Post-structuralist, and other theoretical perspectives applied to your specific essay question." },
      { q: "What referencing style is used for sociology?", a: "Harvard is most common for sociology in the UK, ASA in the US. We support all styles — specify yours when ordering." },
      { q: "Can you write about intersectionality and gender?", a: "Yes. Our writers are well-versed in feminist sociology, intersectionality (Crenshaw), queer theory, and gender studies literature." },
      { q: "Can you help with sociology research methods?", a: "Yes — qualitative methods (interviews, ethnography, focus groups), quantitative methods (surveys, statistics), and mixed-methods designs." },
      { q: "How fast can a sociology essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Longer papers and dissertations need 6–24 hours." },
    ],
    relatedSubjects: ["psychology", "history", "political-science"],
  },
  {
    slug: "economics",
    name: "Economics",
    heroHeading: "Economics Essay & Assignment Writing Service — Expert Help, Fast",
    heroSub: "Get economics essays, reports, and research papers written by economics graduates. Macro, micro, and econometrics covered. From $15/page.",
    description: "Our economics writers hold BSc and MSc Economics from leading universities. They understand microeconomic and macroeconomic theory, econometric analysis, game theory, and the policy frameworks your assignments require.",
    paperTypes: ["Economics essays", "Research papers", "Econometric reports", "Policy analysis", "Economic case studies", "Economics dissertations", "Literature reviews", "Mathematical economics papers"],
    topics: ["Microeconomics", "Macroeconomics", "Monetary policy", "Fiscal policy", "International trade", "Game theory", "Development economics", "Behavioural economics"],
    color: "from-green-600 to-emerald-400",
    keywords: ["economics essay writing service", "write my economics essay", "economics paper help", "pay someone to write economics essay", "economics assignment help", "macroeconomics essay help", "microeconomics essay writing service", "urgent economics essay help", "buy economics essay online", "economics dissertation writing service"],
    faqs: [
      { q: "Can you write micro and macroeconomics essays?", a: "Yes — supply and demand, market structures, fiscal and monetary policy, GDP, inflation, unemployment, trade theory, and more." },
      { q: "Can writers handle mathematical economics?", a: "Yes. Our economics writers handle mathematical models, diagrams, and quantitative analysis including regression and econometrics." },
      { q: "What referencing style is used for economics?", a: "APA and Harvard are most common for economics. Chicago is used in some US programmes. Specify yours when ordering." },
      { q: "Can you write an economics policy analysis?", a: "Yes — policy briefs, impact assessments, and critical analysis of economic policies with reference to real-world data and peer-reviewed literature." },
      { q: "How fast can an economics essay be delivered?", a: "Essays of 1,500–2,500 words can typically be delivered in 1–3 hours. Research papers with data analysis need 6–12 hours." },
    ],
    relatedSubjects: ["business", "political-science", "sociology"],
  },
  {
    slug: "english-literature",
    name: "English & Literature",
    heroHeading: "English Literature Essay Writing Service — Expert Writers, Fast",
    heroSub: "Get English literature essays, critical analyses, and dissertations written by literature graduates. Delivered in 1–24 hours. From $15/page.",
    description: "Our English literature writers hold degrees in English Language, Literature, and Creative Writing from leading universities. They produce close reading analyses, comparative essays, and literary criticism across all periods — from Shakespeare to contemporary fiction.",
    paperTypes: ["Literary analysis essays", "Comparative essays", "Close reading papers", "Poetry analysis", "Dissertation chapters", "Book reviews", "Critical theory papers", "Creative writing assignments"],
    topics: ["Shakespeare & Renaissance", "Victorian literature", "Modernism & postmodernism", "Postcolonial literature", "American literature", "Poetry analysis", "Gothic literature", "Contemporary fiction"],
    color: "from-indigo-600 to-blue-400",
    keywords: ["English literature essay writing service", "write my English essay", "literature essay help", "pay someone to write English essay", "English assignment help", "literary analysis writing service", "Shakespeare essay help", "urgent English literature essay", "buy English essay online", "English literature dissertation help"],
    faqs: [
      { q: "Can you analyse any novel or poem?", a: "Yes — Shakespeare, Chaucer, Milton, Austen, Dickens, Woolf, Toni Morrison, Chinua Achebe, and any other text. Share the text and your question." },
      { q: "Can writers apply literary theory?", a: "Yes — feminist criticism, Marxist criticism, postcolonial theory, psychoanalytic criticism, New Historicism, and deconstruction applied to your text." },
      { q: "What referencing style is used for English literature?", a: "MLA is standard for English literature in the US. MHRA is common in the UK. We support both, plus Chicago and Harvard." },
      { q: "Can you write a comparative literature essay?", a: "Yes — comparing two or more texts, authors, or periods using a structured argument with textual evidence and critical sources." },
      { q: "How fast can a literature essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Dissertations and longer critical papers need 6–24 hours." },
    ],
    relatedSubjects: ["history", "sociology", "political-science"],
  },
  {
    slug: "biology",
    name: "Biology",
    heroHeading: "Biology Essay & Lab Report Writing Service — STEM Experts, Fast",
    heroSub: "Get biology essays, lab reports, research papers, and literature reviews written by qualified biology graduates. From $15/page.",
    description: "Our biology writers hold BSc, MSc, and PhD in biological sciences. They write with scientific accuracy, use peer-reviewed sources, and understand the conventions of scientific writing — from IMRAD-structured lab reports to essay-style biology papers.",
    paperTypes: ["Biology essays", "Lab reports", "Research papers", "Literature reviews", "Biology case studies", "Scientific reports", "Dissertation chapters", "Data analysis write-ups"],
    topics: ["Cell biology & genetics", "Human anatomy & physiology", "Microbiology", "Ecology & environmental biology", "Molecular biology", "Evolutionary biology", "Biochemistry", "Marine biology"],
    color: "from-emerald-600 to-green-400",
    keywords: ["biology essay writing service", "write my biology essay", "biology lab report help", "pay someone to write biology essay", "biology assignment help", "biology research paper writing service", "urgent biology essay help", "buy biology essay online", "biology dissertation writing service", "biology paper writer for hire"],
    faqs: [
      { q: "Can you write a biology lab report?", a: "Yes — including abstract, introduction, materials & methods, results, discussion, and conclusion. Writers follow IMRAD structure and your department's guidelines." },
      { q: "Do biology writers use peer-reviewed sources?", a: "Yes. Writers cite from PubMed, Nature, Science, Cell, and other peer-reviewed journals. You can also request specific sources." },
      { q: "Can you write about genetics or molecular biology?", a: "Yes — DNA replication, gene expression, CRISPR, epigenetics, molecular cloning, and other advanced molecular biology topics." },
      { q: "What referencing style is used for biology?", a: "APA and Vancouver are most common for biology. Some departments use CSE or APA. Specify yours when ordering." },
      { q: "How fast can a biology essay be written?", a: "Essays of 1,500–2,000 words can be delivered in 1–3 hours. Lab reports and research papers with data analysis need 3–6 hours." },
    ],
    relatedSubjects: ["nursing", "psychology", "economics"],
  },
  {
    slug: "political-science",
    name: "Political Science",
    heroHeading: "Political Science Essay Writing Service — Expert Help, Fast",
    heroSub: "Get political science essays, research papers, and dissertations written by politics graduates. Delivered in 1–24 hours. From $15/page.",
    description: "Our political science writers hold degrees in Politics, International Relations, and Public Policy. They understand political theory, comparative politics, IR frameworks, and the empirical and normative analysis your assignments require.",
    paperTypes: ["Political science essays", "IR research papers", "Policy analysis", "Comparative politics papers", "Political theory essays", "Dissertations", "Literature reviews", "Position papers"],
    topics: ["Political theory & philosophy", "International relations", "Comparative politics", "Public policy", "Democracy & governance", "Nationalism & identity", "Human rights & security", "US/UK politics"],
    color: "from-red-600 to-orange-400",
    keywords: ["political science essay writing service", "write my politics essay", "international relations essay help", "pay someone to write politics essay", "political science assignment help", "IR essay writing service", "public policy essay help", "urgent political science essay", "buy politics essay online", "political science dissertation help"],
    faqs: [
      { q: "Can you write about international relations theories?", a: "Yes — Realism, Liberalism, Constructivism, Marxism, Feminism in IR, and Post-structuralism applied to your specific question." },
      { q: "Can writers write about US or UK politics?", a: "Yes — the US Electoral College, Congress, Supreme Court, UK Parliament, Westminster system, devolution, Brexit, and more." },
      { q: "Can you write a comparative politics essay?", a: "Yes — comparing political systems, parties, elections, or policies across two or more countries with structured analysis." },
      { q: "What referencing style is used for political science?", a: "Chicago and Harvard are most common for political science. APA is used in some US programmes. Specify yours when ordering." },
      { q: "How fast can a politics essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Research papers and dissertations need 6–24 hours." },
    ],
    relatedSubjects: ["law", "history", "sociology"],
  },
  {
    slug: "marketing",
    name: "Marketing",
    heroHeading: "Marketing Essay & Assignment Writing Service — Expert Help, Fast",
    heroSub: "Get marketing essays, plans, and case studies written by marketing professionals and MBA graduates. Delivered in 1–24 hours. From $15/page.",
    description: "Our marketing writers combine academic knowledge with real-world marketing experience. They understand consumer behaviour, digital marketing, brand strategy, the 4Ps/7Ps, and the analytical frameworks used in marketing programmes at all levels.",
    paperTypes: ["Marketing essays", "Marketing plans", "Brand analysis", "Consumer behaviour papers", "Digital marketing reports", "Market research papers", "Advertising case studies", "Marketing dissertations"],
    topics: ["Digital marketing & SEO", "Consumer behaviour", "Brand management", "Marketing strategy", "Social media marketing", "Content marketing", "Market research & analysis", "International marketing"],
    color: "from-pink-600 to-rose-400",
    keywords: ["marketing essay writing service", "write my marketing essay", "marketing assignment help", "pay someone to write marketing essay", "marketing plan writing service", "digital marketing essay help", "marketing dissertation writing", "urgent marketing essay help", "buy marketing essay online", "marketing case study writing service"],
    faqs: [
      { q: "Can you write a full marketing plan?", a: "Yes — situational analysis (SWOT, PESTLE), target market, marketing mix (4Ps/7Ps), digital strategy, budget, and implementation plan." },
      { q: "Can writers write about digital marketing?", a: "Yes — SEO, PPC, social media marketing, content marketing, email marketing, influencer marketing, and analytics." },
      { q: "Can you analyse a real brand or campaign?", a: "Yes. Writers analyse real brands (Nike, Coca-Cola, Apple, etc.) using marketing frameworks and credible secondary data." },
      { q: "What referencing style is used for marketing?", a: "Harvard is most common for marketing in UK programmes. APA is standard in the US. Specify yours when ordering." },
      { q: "How fast can a marketing essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Full marketing plans and dissertations need 12–24 hours." },
    ],
    relatedSubjects: ["business", "economics", "sociology"],
  },
  {
    slug: "education",
    name: "Education",
    heroHeading: "Education Essay & Assignment Writing Service — Expert Help, Fast",
    heroSub: "Get education essays, lesson plans, research papers, and dissertations written by qualified teachers and education researchers. From $15/page.",
    description: "Our education writers include qualified teachers, school leaders, and education researchers. They understand pedagogy, curriculum theory, educational policy, and the reflective practice expected in education programmes at undergraduate and postgraduate level.",
    paperTypes: ["Education essays", "Lesson plans", "Reflective journals", "Research papers", "Education dissertations", "Literature reviews", "Policy analysis", "Teaching philosophy statements"],
    topics: ["Pedagogy & teaching methods", "Curriculum design", "Special educational needs (SEN)", "Early childhood education", "Educational psychology", "Inclusive education", "Educational policy", "Assessment & feedback"],
    color: "from-teal-600 to-cyan-400",
    keywords: ["education essay writing service", "write my education essay", "education assignment help", "pay someone to write education essay", "teaching essay writing service", "education dissertation help", "pedagogy essay help", "urgent education essay writing", "buy education essay online", "education research paper writing service"],
    faqs: [
      { q: "Can you write a reflective teaching journal?", a: "Yes — using Gibbs, Brookfield, Schön, or whichever reflective model your programme requires. Writers draw on real classroom scenarios and educational theory." },
      { q: "Can you write about SEN and inclusion?", a: "Yes — special educational needs, autism spectrum, dyslexia, EHCP plans, inclusive classroom strategies, and relevant legislation (SEND Code of Practice, IDEA)." },
      { q: "Can writers write a lesson plan?", a: "Yes — complete lesson plans with learning objectives, differentiation strategies, assessment methods, and curriculum alignment." },
      { q: "What referencing style is used for education?", a: "APA is standard for education in the US. Harvard is most common in UK education programmes. Specify yours when ordering." },
      { q: "How fast can an education essay be written?", a: "Essays of 1,500–2,500 words can be delivered in 1–3 hours. Dissertations and research papers need 6–24 hours." },
    ],
    relatedSubjects: ["psychology", "nursing", "sociology"],
  },
];

export function getSubject(slug: string): SubjectData | undefined {
  return SUBJECTS.find((s) => s.slug === slug);
}

export function getAllSubjectSlugs(): string[] {
  return SUBJECTS.map((s) => s.slug);
}
